const moods=window.JHUMO_MOODS||[],songs=window.JHUMO_SONGS||[];
let currentMood=null,queue=[],currentIndex=0,player=null,playerReady=false;
const $=id=>document.getElementById(id),moodsEl=$("moods"),playlistEl=$("playlist"),titleEl=$("songTitle"),artistEl=$("songArtist"),moodLabelEl=$("moodLabel"),moodBadge=$("moodBadge"),trackCountEl=$("trackCount"),queueHeadingEl=$("queueHeading"),emptyState=$("emptyState"),playBtn=$("playBtn");
function safe(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderMoods(){moodsEl.innerHTML=moods.map(m=>`<button class="mood ${currentMood===m.id?"active":""}" data-mood="${m.id}" style="--c:${m.color}"><span class="mood-icon">${m.icon}</span><span class="mood-name">${safe(m.name)}</span><span class="mood-line">${safe(m.line)}</span></button>`).join("");document.querySelectorAll(".mood").forEach(b=>b.onclick=()=>selectMood(b.dataset.mood,true))}
function selectMood(id,autoPlay=false){currentMood=id;queue=songs.filter(s=>(s.moods||[]).includes(id));currentIndex=0;renderMoods();renderQueue();const m=moods.find(x=>x.id===id);moodLabelEl.textContent=`JHUMO • ${m?.name||""}`;moodBadge.textContent=m?.name||"JHUMO";queueHeadingEl.textContent=m?.name||"Your queue";trackCountEl.textContent=`${queue.length} ${queue.length===1?"pick":"picks"}`;if(queue.length){loadTrack(0,autoPlay);if(autoPlay)$("playerSection").scrollIntoView({behavior:"smooth",block:"center"})}}
function renderQueue(){if(!queue.length){playlistEl.innerHTML=`<div class="track" style="cursor:default"><div class="track-num">♪</div><div><div class="track-title">Choose a mood to see your queue</div><div class="track-artist">JHUMO keeps it simple.</div></div><div class="track-go">+</div></div>`;return}playlistEl.innerHTML=queue.map((s,i)=>`<div class="track ${i===currentIndex?"current":""}" data-index="${i}"><div class="track-num">${String(i+1).padStart(2,"0")}</div><div><div class="track-title">${safe(s.title)}</div><div class="track-artist">${safe(s.artist)}</div></div><div class="track-go">▶</div></div>`).join("");document.querySelectorAll(".track[data-index]").forEach(r=>r.onclick=()=>loadTrack(Number(r.dataset.index),true))}
function loadTrack(index,autoPlay=true){if(!queue.length)return;currentIndex=(index+queue.length)%queue.length;const s=queue[currentIndex];titleEl.textContent=s.title;artistEl.textContent=s.artist;emptyState.style.display="none";renderQueue();if(playerReady&&player){autoPlay?player.loadVideoById(s.youtubeId):player.cueVideoById(s.youtubeId)}}
function nextTrack(){if(queue.length)loadTrack(currentIndex+1,true)}function prevTrack(){if(queue.length)loadTrack(currentIndex-1,true)}
function surprise(){const available=moods.filter(m=>songs.some(s=>(s.moods||[]).includes(m.id)));const m=available[Math.floor(Math.random()*available.length)];selectMood(m.id,false);currentIndex=Math.floor(Math.random()*queue.length);loadTrack(currentIndex,true);$("playerSection").scrollIntoView({behavior:"smooth",block:"center"})}
window.onYouTubeIframeAPIReady=function(){player=new YT.Player("youtubePlayer",{height:"100%",width:"100%",videoId:"",playerVars:{controls:1,rel:0,playsinline:1},events:{onReady:()=>{playerReady=true},onStateChange:e=>{if(e.data===YT.PlayerState.ENDED)nextTrack();if(e.data===YT.PlayerState.PLAYING)playBtn.textContent="Ⅱ";if(e.data===YT.PlayerState.PAUSED||e.data===YT.PlayerState.CUED)playBtn.textContent="▶"}}})};
playBtn.onclick=()=>{if(!playerReady||!player)return;if(!queue.length){surprise();return}player.getPlayerState()===YT.PlayerState.PLAYING?player.pauseVideo():player.playVideo()};
$("nextBtn").onclick=nextTrack;$("prevBtn").onclick=prevTrack;$("surpriseBtn").onclick=surprise;$("surpriseTop").onclick=surprise;
renderMoods();renderQueue();